#!/usr/bin/env bash

set -euo pipefail

# Add the lib directory to the Bash load path
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/environment.bash
. "$DIR/../lib/environment.bash"

function main() {
    hello_bash
}

main