#!/usr/bin/env node

// Add the lib directory to the Node load path
const path = require('path');
const { helloNode } = require(path.join(__dirname, '../lib/post-command'));

function main() {
    helloNode();
}

main();
