#!/usr/bin/env python3
import sys
import os

# Add the lib directory to the Python load path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'lib'))

from pre_command import hello_python

def main():
    hello_python()

main()